# Generated by Django 2.1.5 on 2019-02-28 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190227_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='date',
            new_name='post_date',
        ),
    ]
